$(document).ready(function(){
  $(".link-btn").click(function(){
    $(".main-title").toggle();
    $(".title").toggle();
    $(".contact").toggle();
    $(".image_me").toggle();
    $("#projects").toggle();
  })
})